### ISSUE TITLE
*zenq.ZenQ.Read() eat 100% CPU

### ISSUE THREAD

**Issue by zxp** [alphadose/ZenQ#12]
I have a goroutine read a value from zenq queue in a for loop, but the Read() function use the whole cpu. 

<img width="364" alt="image" src="https://user-images.githubusercontent.com/869234/190405270-30ef3c10-96c3-481f-9536-8c38d71dded9.png">
<img width="604" alt="image" src="https://user-images.githubusercontent.com/869234/190405498-0de71c6b-5058-445c-a5fc-d2552036812f.png">

when I comment these Read() function and recompile the cpu usage drop to zero.
<img width="515" alt="image" src="https://user-images.githubusercontent.com/869234/190405887-bf35babb-48ec-4a99-bf67-3eb2a48c5841.png">
<img width="617" alt="image" src="https://user-images.githubusercontent.com/869234/190405976-cd48b2b7-b2c6-4845-beb8-50dda59f7afc.png">

I tried run profile this program , the top10 cum shows
<img width="569" alt="image" src="https://user-images.githubusercontent.com/869234/190406863-0894c8b0-0da9-48d5-bc4a-bc9f456e233d.png">

Please tell me how to solve this problem, thank you!

**Comment by alphadose** [comment]
@zxp ZenQ does active spinning during the `Read()` operation to guarantee low latency i.e the Read() goroutine will always run or context-switch via `runtime.Gosched()` in case slot is empty This is a design choice that optimizes more towards low-latency and less towards resource conservation.

Hence, ZenQ Read() will always be hungry for CPU. If your use case requires lower CPU consumption then channels would be better.

**Comment by zxp** [comment]
Thanks for the reply, I see, I have switched to the native channel mode and it works fine now.
